#!/usr/bin/env python

import sys
import os

def process_file(arg):
	if os.path.isdir(arg):
		for fname in os.listdir(arg):
			process_file(os.path.join(arg,fname))
	elif os.path.isfile(arg):
		f = open(arg)
		data = f.read()
		f.close()
		print arg, data.count('('), data.count(')')

if len(sys.argv) == 1:
	data = sys.stdin.read()
	print data.count('('), data.count(')')
else:
	process_file(sys.argv[1])

